name: Unit tests

on:
  pull_request:
    paths:
      - 'projects/**'
      - '!projects/*testing/**'
      - '!projects/demo/**'
      - '!projects/icons/**'
      - '.github/workflows/test.yml'
      - 'angular.json'
      - 'package.json'
      - 'karma.conf.js'
      - 'karma.config.js'
      - 'tsconfig*'
  push:
    branches:
      - main
      - '!release/**'

env:
  NX_BRANCH: ${{ github.event.number }}
  FIREBASE_CONFIG: ${{ secrets.FIREBASE_CONFIG }}
  IS_MAIN_BRANCH: ${{ github.ref == 'refs/heads/main' }}

jobs:
  test:
    name: Karma
    # Setup part
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
        with:
          fetch-depth: 0
      - name: Use Node.js
        uses: actions/setup-node@v1
        with:
          node-version: '12.x'
      # Setup cache
      - name: Restore node_modules from cache
        id: cache-node-modules
        uses: actions/cache@v2
        with:
          path: |
            node_modules
            !node_modules/.cache/
          key: node-modules-cache-${{ hashFiles('**/package-lock.json') }}
      - name: Restore from global NPM cache
        if: steps.cache-node-modules.outputs.cache-hit != 'true'
        uses: actions/cache@v2
        with:
          path: ~/.npm
          key: npm-cache-${{ hashFiles('**/package-lock.json') }}
          restore-keys: npm-cache-
      - name: Restore from cache of builds
        id: build-cache
        uses: actions/cache@v2
        with:
          path: node_modules/.cache
          key: builds-cache-${{ hashFiles('**/package-lock.json') }}-${{ github.ref }}
          restore-keys: builds-cache-${{ hashFiles('**/package-lock.json') }}
      - name: Clean install dependencies
        if: steps.cache-node-modules.outputs.cache-hit != 'true'
        run: npm ci
      # End of setup cache
      # End of setup
      - name: Run all tests for get coverage (with nx cache)
        run: npm run run-many:test:libs

      - uses: codecov/codecov-action@v2
        with:
          directory: ./coverage/kit/
          flags: summary,kit
          name: kit
      - uses: codecov/codecov-action@v2
        with:
          directory: ./coverage/core/
          flags: summary,core
          name: core
      - uses: codecov/codecov-action@v2
        with:
          directory: ./coverage/cdk/
          flags: summary,cdk
          name: cdk
      - uses: codecov/codecov-action@v2
        with:
          directory: ./coverage/addon-tablebars/
          flags: summary,addon-tablebars
          name: addon-tablebars
      - uses: codecov/codecov-action@v2
        with:
          directory: ./coverage/addon-table/
          flags: summary,addon-table
          name: addon-table
      - uses: codecov/codecov-action@v2
        with:
          directory: ./coverage/addon-mobile/
          flags: summary,addon-mobile
          name: addon-mobile
      - uses: codecov/codecov-action@v2
        with:
          directory: ./coverage/addon-editor/
          flags: summary,addon-editor
          name: addon-editor
      - uses: codecov/codecov-action@v2
        with:
          directory: ./coverage/addon-doc/
          flags: summary,addon-doc
          name: addon-doc
      - uses: codecov/codecov-action@v2
        with:
          directory: ./coverage/addon-commerce/
          flags: summary,addon-charts
          name: addon-commerce
      - uses: codecov/codecov-action@v2
        with:
          directory: ./coverage/addon-charts/
          flags: summary,addon-charts
          name: addon-charts

concurrency:
  group: test-${{ github.head_ref }}
  cancel-in-progress: true
